### ISSUE TITLE
Installation into Program Files causes permissions issue on ini file

### ISSUE THREAD

**Issue by rogerclarkmelbourne** [rogerclarkmelbourne/radioddity_gd-77_cps2.0.5#22]
As the language can now be changed, this causes a problem because the CPS uses setup.ini file to store the language setting

**Comment by rogerclarkmelbourne** [comment]
I've now done a temporary fix for this by changing the installer to install into the top of the 'system drive'

See https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/commit/7f89ca8718c21edeeb91d53a61162c3167966c1d

In the longer term, setup.ini should not be used to store changes to config. This should be done in using the registry

**Comment by dg9vh** [comment]
Isn't this a doublette of https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/issues/18?

**Comment by rogerclarkmelbourne** [comment]
Yes. I will close this as its a duplicate
