### ISSUE TITLE
DataToByte() bug creating Encrypt form data

### ISSUE THREAD

**Issue by lxa520** [rogerclarkmelbourne/radioddity_gd-77_cps2.0.5#42]
https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/master/DMR/MainForm.cs

line 3006 

tmp = Common.StructToBytes(EncryptForm.data, Marshal.SizeOf(EncryptForm.data.GetType()));

**Comment by rogerclarkmelbourne** [comment]
LOL

You have the original source

My version looks like this

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/master/DMR/MainForm.cs#L3006

As I don't know many of the variable names

**Comment by lxa520** [comment]
i wont use github;

this function is DataToByte
array2 = Settings.smethod_61(EncryptForm.data, Marshal.SizeOf(EmergencyForm.data.GetType()));
			Array.Copy(array2, 0, array, Settings.ADDR_ENCRYPT, array2.Length);

the length is wrong, Marshal.SizeOf(EmergencyForm.data.GetType())

**Comment by rogerclarkmelbourne** [comment]
OK
I will check my code

**Comment by rogerclarkmelbourne** [comment]
BTW. I tried to email you at qq.com but it bounced :-(

**Comment by rogerclarkmelbourne** [comment]
BTW. You know the version of WinForms.UI you are using is old
There is a newer version, which I used.  Just some small changes to API (I think 2 or 3 lines changed in Mainform.cs)

I will probably add WinformsUI as a sub project

**Comment by rogerclarkmelbourne** [comment]
Also BTW. What version of VS are you using. It seems quite old, but it could be a problem with decompiling that makes it seem like you are using .Net 2.0

**Comment by rogerclarkmelbourne** [comment]
ALso BTW. You dont need the STM dll files. They are no longer used as the codeplug comms are not different from the MD-380

**Comment by rogerclarkmelbourne** [comment]
Also BTW Did you write Baofeng RD-5R CPS. Its very similar to GD-77 CPS but I have not managed to decompile yet, as it still does not run OK for me :-(

**Comment by lxa520** [comment]
MD-380 is dfu

**Comment by lxa520** [comment]
i use net 3.5

**Comment by rogerclarkmelbourne** [comment]
OK. Thanks

**Comment by rogerclarkmelbourne** [comment]
OK
I see the bug

array2 = Settings.smethod_61(EncryptForm.data, Marshal.SizeOf(EmergencyForm.data.GetType()));

Line 3053 in  my code 

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/blob/master/DMR/MainForm.cs#L3053

Size for EmergencyForm is used for EncryptForm

I will change this

**Comment by rogerclarkmelbourne** [comment]
Sorry wrong line in my code

I use development branch for latest changes on my machine

So line if 3053 for me because of additions "Extra" menu etc

**Comment by lxa520** [comment]
Ok

**Comment by rogerclarkmelbourne** [comment]
Thanks

Should be fixed in development branch commit

https://github.com/rogerclarkmelbourne/radioddity_gd-77_cps2.0.5/commit/752daacff79cfa0feef065d5cc0737b215c72db5
